doc/book/ipl.tex
ipl/procs/options.icn

Mods to ipl/procs/options plus a modified description in appendix B of the book.

New options

---

src/runtime/rcoexpr.r

In two parts: (1) The fix, (2) The cosmetic clean up of leading whitespace.

Fix ns leak

---

ipl/procs/paths.icn

Patch supplied by Steve Wampler; see
https://sourceforge.net/p/unicon/mailman/unicon-ldif/?viewmonth=201912

Fix a problem with using space-separated IPATH and LPATH settings

---

doc/ib/ib.tex
doc/ib/p1-iconOverview.tex
doc/ib/p3-concur.tex

Also clean up tables and fix many of the references (in red) to the
original source document. Some references are still to-do.

Provide missing figures for IB chapter 32.

---

configure
configure.ac
src/iconc/ccomp.c
src/runtime/fxposix.ri
src/runtime/rstruct.r

I have not tested on Windows, but at least iconc builds successfully now. src/iconc/ccomp.c might require more work.

Enable iconc on all platforms by default 

---

doc/ib/appD.tex
doc/ib/p1-runTime.tex
src/runtime/rmemmgt.r

Also fix -Wpointer-to-int-cast warnings from the Windows 32 bit compiler.

Add more types to the heap verifier.

---

Makefile
Makefile.in

Fix revision.h location

---

uni/lib/complex.icn

A complex number class supporting operator overloading of +,-,*,/

Support complex numbers, including operator overloading.

---

uni/lib/Makefile
uni/lib/complex.icn
uni/lib/predicat.icn

-- Fix typos in comments in complex.icn
-- Extend istype() in predicat.icn to test against class instances
-- Update Makefile to build complex.u and predicat.u

-- Add complex.u and predicat.u to Makefile

---

ipl/procs/paths.icn
src/common/filepart.c
src/common/mlocal.c

IPATH and LPATH should be honored over built-in paths
Fix pathsep used by icont

IPATH and LPATH fixes

---

src/runtime/rwindow.r

GCC 10: Missed a spot in the graphics subsystem

---

doc/book/struct.tex
src/runtime/data.r

Enhance UB and error 120 text to clarify set operations on tables.

Enhance UB and error 120 text to clarify set operations on tables

---

ipl/procs/io.icn

ipl: Fix io.icn missing "link getpaths"

---

.gitignore
uni/lib/args.icn

Two changes:
(a) let parameter "--" denote end of all options, everything after that is an argument.
(b) updated .gitignore to ignore more compiled programs.

Updates to args.icn

---

src/h/cpuconf.h

Don't overlap flags with large string size

---

ipl/procs/itokens.icn

This update now includes reserved word specific to Unicon, as well as
the new operators specific to Unicon and additional features such
as list comprehension.

Update itokens.icn to handle additional Unicon features.

---

uni/gprogs/abook.icn

Provides a simple addressbook app.  Only tested under Linux, with PostgreSQL.

Address book

---

uni/lib/Makefile
uni/lib/exception.icn
uni/progs/exception_demo.icn

Exception class updated with new convenience methods.  Makefile modified so exception.u built after fcn_util.u.  New demo program added.

Fixes to Exception

---

ipl/procs/escape.icn
uni/lib/json.icn

A. Extends escape(s) in IPL escape.icn to also handle unicode encodings.
B. Fixes control-character processing in json.icn.
C. Adds simplified interface procedures into JSON.

JSON update

---

src/runtime/rsys.r

Fix crash on macOS if libz is enabled

---

src/runtime/rstruct.r

Make cpslots() aware of arrays

---

.github/workflows/ccpp.yml
.gitignore
Makedefs.in
Makefile
Makefile.in
config/scripts/version.sh
configure
configure.ac
src/h/version.h
src/runtime/Makefile

Move git commands to a script for better handling of out of tree
builds. Refactor/cleanup some rules. Update the connfigure script
to use the new version script. Writeo ut two new summary files:
* Configuration summary: unicon-config.log
* Features Summary: unicon-features.log

Improve git commands and version handling

---

README.md

readme: update build instructions and drop outdated info [skip ci]

---

config/scripts/version.sh
src/h/sys.h
src/iconc/ccomp.c

Fix macOS iconc and remove warnings

---

src/h/config.h
src/runtime/fmisc.r
src/runtime/fmonitr.r
src/runtime/oasgn.r
src/runtime/rcoexpr.r
src/runtime/rcomp.r
src/runtime/rmemmgt.r
src/runtime/rstruct.r

Allow building with no arrays and no patterns

---

src/runtime/fmisc.r

runtime: account for variable argument functions in localnames

---

.gitignore
Makedefs.in
Makefile
Makefile.in
aclocal.m4
configure
src/common/Makefile
src/gdbm/Makefile
src/iconc/Makefile
src/iconc/ccomp.c
src/iconc/cmain.c
src/icont/Makefile
src/libtp/Makefile
src/preproc/Makefile
src/runtime/Makefile
uni/unicon/unicon.icn

Create unicon/rt/lib and unicon/rt/include  for  runtime libraries.
This will improve binaries mobility and fixe issues after installing Unicon to standard locations

Create unicon/rt subdir for runtime libraries

---

uni/unicon/unicon.icn

Changed from jeffery@cs.uidaho.edu to jeffery@cs.nmt.edu

Update MERRADDRESS to reflect new email address

---

Makefile
Makefile.in
config/win32/gcc/unicon.iss
configure
configure.ac
ipl/procs/paths.icn
src/Makefile
src/iconc/ccomp.c
src/iconc/cmain.c
src/runtime/Makefile
src/xpm/lib/Makefile
uni/unicon/preproce.icn
uni/unicon/unicon.icn

iconc, ipl: improve windows paths

---

src/iconc/cmain.c

-help produces a full list of options in a similar format to that
produced by unicon -help
-version displays the same information as unicon -version

Add -version and -help to iconc

---

src/runtime/Makefile
src/runtime/imain.r

Found a few more link issues when using unicon -C on Windows that weren't 
addressed by my previous PR. This should fix them.

iconc: fix link issues when using unicon -C

---

config/win32/gcc/unicon.iss
uni/Makefile
uni/gui/ivib/Makefile
uni/unidoc/Makefile

UniDoc: set a new default rule. Build Ivib in GUI mode on Windows

---

uni/unidoc/UniAll.icn

Spelling error correction in comment

---

uni/iyacc/main.c
uni/iyacc/output.c

This is a patch from Clint to add the -dd option.

Add -dd option to iyacc (to produce Java compatible definitions).

---

src/h/graphics.h

Signed-off-by: Gigi Young <kzyoung93@gmail.com>

Iconc OpenGL compilation fix

---

doc/book/gui.tex

Fix Label("label=Click to close","pos=50%,33%’, "align=c,c")

Update Gui.tex fix misquote

---

configure
configure.ac
ipl/cfuncs/tconnect.c
src/common/Makefile
src/h/opengl.h
src/h/rmacros.h
src/libtp/tp.c

Add compiler flag std=-c11

---

.github/workflows/ccpp.yml
Makefile
Makefile.in
uni/unidoc/Makefile

Enable htmldoc build in the ci

---

plugins/src/upexample/tests/upex.icn
plugins/src/upexample/upexample.icn

fix upexample plugin, add test example

---

Makefile.in
tests/posix/pty_uni.icn
tests/posix/system.icn
tests/posix/uxsocket.icn
tests/thread/gc.icn

tests: allow tests to run when unicon is not on the path

---

.github/workflows/ccpp.yml
src/h/rmacros.h

Use ISO C __typeof__ as an alternative for __auto_type

---

Makefile
Makefile.in

doc: build full html using unidoc

---

.github/workflows/build.yml

ci: add Oracle Linux 8

---

Makefile
README.md

readme: add discussion about configure script options

---

src/runtime/interp.r
src/runtime/lmisc.r

Allow snd/rcv operators to be used with sockets

---

README.md

Add discussion of library dependencies

---

config/editor/README
config/editor/unicon-notepad++.dark.xml
config/editor/unicon-notepad++.light.xml

Light & Dark themes for Notepad++ for the Unicon language.
Updated README.
Signed-off-by: MatthewCLane <yourcomputerguy.m.lane@gmail.com>

Unicon Themes for Notepad++

---

config/win32/gcc/unicon.iss

config: fix ivib path in Windows installer

---

configure
configure.ac
ipl/cfuncs/icall.h
plugins/src/Makefile
plugins/src/SHA/Makefile
plugins/src/SHA/RFC6234/Makefile
plugins/src/icall.h
src/runtime/fload.r

The first commit puts in "the plumbing" for cnv_c_str on Windows.
The second commit enables the SHA plugin.

Re-enable sha

---

Makedefs.in
configure
configure.ac
plugins/src/Makefile
plugins/src/sqlite/Makefile
plugins/src/sqlite/sqlite.c
plugins/src/sqlite/sqlite.h
plugins/src/sqlite/sqlite.icn
plugins/src/sqlite/testSQLite.icn
src/h/auto.in

The plugin is not built If the sqlite3 files that it depends
on (sqlite3.h and libsqlite3.so) are not found. The check is done
when building the Unicon system.

Initial version of the SQLite interface plugin.

---

Makedefs.in
src/runtime/rsys.r

runtime: don't count a sleeping as a running thread

---

src/runtime/oref.r

Exepcted behavior for !socket in this order:
returns the next line availble to read
returns whatever is available If no full line is available
blocks waiting for input there is no data to read

runtime: add support for ! operation to sockets

---

src/runtime/fload.r

Replicate the logic used by Unix code to search for a library in the Windows build. Additionally, if lib.so is not found, try lib.dll

loadfunc mods for Windows

---

uni/Makefile
uni/ulsp/Makefile
uni/ulsp/README.md
uni/ulsp/completion.icn
uni/ulsp/database.icn
uni/ulsp/launch-lsp.icn
uni/ulsp/server.icn
uni/ulsp/workspace.icn

This feature is built in accordance to the Language Server Protocol (LSP).
Sources: 
- General overview of LSP: https://microsoft.github.io/language-server-protocol/
- LSP Specification: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/
Description:
Added new package, ulsp, to unicon/uni directory. Currently utilizing VS Code client for testing/debugging. The VS Code client implementation can be found at: https://github.com/HereBeCode/unicon-lsp
Current LSP Capabilities:
- textDocument/Synchronization
- textDocument/Completion
Future LSP Capabilities:
- Additional capabilities to be implemented can be found here: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#languageFeatures

Add Unicon Language Server Protocol Support

---

doc/book/install.tex

Remove explicit build instructions for each platform and refer to README. Add links to GitHub and SourceForge repositories.

Update Unicon book Appendix F (Installation).

---

doc/book/ucl.tex

Add a short description of plugins (which could perhaps be extended) plus a description of the Bitman plugin to Appendix C.

Add the Bitman plugin to Appendix C of the Unicon book.

---

uni/udb/breakpoint.icn
uni/udb/help.icn

This will help solve an adapter problem in the future.

udb: Add cmd 'clear break [file] all'

---

tests/unicon/FxPtTests.icn
tests/unicon/stand/FxPtTest.std
tests/unicon/stand/FxPtTest_OVLD.std
uni/lib/FxPt.icn

Correct the div method to give control over the number of places. Fix the div method to give the correct rounding.
Add tests for the above.
Add the type names that are used by iconc.

Corrections to the fixed point arithmetic class.

---

src/runtime/rmsg.r

MaddtoHeader now manages the trailing zero character explicitly (which means that nleft must be initialised with one more character than previously). Using memcpy is more efficient because the existing string length does not have to be calculated; it also removes the stringop-overflow warning.
This change enables the following ci jobs to be built with -Werror enabled: macOS
Ubuntu 20.04
Ubuntu 22.04
CentOS 7
Fedora Latest
Debian 10
Debian 11
Oracle Linux 8
Thin Build

rmsg.r: Replace strncat with memcpy in MaddtoHeader

---

src/runtime/cnv.r

The previous code had two problems:
(1) Overflows were sometimes not detected when the string had a suffix. (2) Strings with a suffix that were big integers would fail (strings
with suffixes that were not a big integer worked).
This commit also fixes a related bug in numeric(), which uses string conversion.

runtime: Fix bugs in string to int conversion when the str has a suffix

---

uni/udb/adapter.icn
uni/udb/console.icn
uni/udb/state.icn

Merging this requires that the marketplace extension for VSCode is updated with the latest changes.
https://github.com/mstreeter10/vscode-unicon-debug

udb: adapter cleanup

---

src/common/uconsole.c
src/h/config.h
src/h/feature.h
src/h/graphics.h
src/h/grttin.h
src/h/rmacros.h
src/h/rproto.h
src/h/xwin.h
src/runtime/Makefile
src/runtime/fmonitr.r
src/runtime/fsys.r
src/runtime/fwindow.r
src/runtime/rmemmgt.r
src/runtime/rmswin.ri
src/runtime/ropengl.ri
src/runtime/rstruct.r
src/runtime/rwin3d.ri
src/runtime/rwindow.r
src/runtime/rwinrsc.r
src/runtime/rwinsys.r
src/runtime/rxrsc.ri
src/runtime/rxwin.ri

This reverts commit 28662317dbf3874922a430032c826149b7ede825, reversing
some changes made to b2e750f00be0bf30be92f5ccdea709761ff87163.
Leaving fonts, UTR22, and ropengl2d.ri in sources.

Partially revert RR #125 OpenGL2D"

---

src/asm/arm_64_macos-rswitch.s

Largely untested, but the logic should be right.
Replaces https://github.com/uniconproject/unicon/pull/505

Adding native coswitch for aarch64/macOS

---

.github/workflows/build.yml

- add Ubuntu 24.04
- add Rocky Linux 9
- drop emulated ARM 32/64
- add native Arm64
- pin Fedora 41 (Fedora latest  42 is still "too new")

ci: add ubuntu24 and rocky linux 9, move arm to native only

---

uni/lib/fastprime.icn
uni/lib/matrix_util.icn

Renames pow() to powm().
Adds all_factors(), gen_factors(), and getfactor().

Avoid name collision with ipl, add fast factoring of large integers
