src/icont/mkkwd.icn
This version uses the previous contents of keyword.h to preserve
existing keyword values before overwriting the file. New keywords
have a value that is higher than all the existing keywords.
Deleting a keyword leaves a "hole" in the sequence of values.
The definitions are written in alphabetical order, as before.
=> New version of mkkwd.icn that preserves keyword values.

doc/book/langref.tex, src/h/feature.h, uni/unicon/preproce.icn
_DEVMODE is defined by the preprocessor when unicon is configured with
--enable-devmode. It enables unicon programs to use $ifdef _DEVMODE to
do different things if the system has been built in developer mode
(e.g. call built-in functions that are not available normally).
=> Add _DEVMODE unicon preprocessor predefined symbol

ipl/procs/numbers.icn
The previous version of large() could erroneously report a native
integer as large if another thread made a concurrent storage allocation.
This version is about 50% slower, so the previous routine is retained
for use if "concurrent threads" is not in the implementation's features.
=> Add thread-safe version of large()

src/runtime/fmisc.r
Most of the changes are whitespace. Is there a way to get a -w option into the diff?
=> Make the answers returned by keyword("allocate") a consistent snapshot.

doc/book/string.tex
The chapter referred to is in lexyacc.tex, which was removed from
the Unicon book in Jan 2013 (commit 86fb4aad). It is still in the
distribution and will be incorporated into a new document.
=> Remove a fossil reference to chapter 18 from the book

ipl/procs/options.icn
The code used to overwrite the value of the _previous_ option
to a non alphanumeric option. (So an option string like
"-wait+ -?" ended up being parsed as "-wait! -?").
=> Fix a problem with non alphanumeric options.

doc/ib/p1-exprEval.tex, doc/ib/p1-iconOverview.tex, doc/ib/p1-procs-coexprs.tex, doc/ib/p1-sets-tables.tex, doc/ib/p1-strings-csets.tex, doc/ib/p1-values.tex
IdxGen allows minuses as part of a word (so "virtual-machine" is
treated as a single word). But a naked em-dash without a space
separating the two words effectively concatenates the words, so in
Strings in Icon are atomic---there are no operations ...
the 5th word in the sentence is "atomic---there" from idxGen's
point of view, thus defeating a match like
"(S|s)tring(|s)+5+(A|a)tomic(|ity)".
The solution is to change "atomic---there" into "atomic{---}there".
=> IB: Prevent em-dashes from interfering with index term matching.

doc/ib/Makefile
An index hit inside an \iconline environment can end up with an extra space
in it, which makeindex treats as different (so we get duplicate entries).
Floating the index hit to outside \iconline solves the problem.
=> IB: Use the idxGen -float option to prevent duplicate index entries.

src/runtime/rstruct.r
rstruct.r had an error (brackets missing around a cast) that caused
a compilation failure.
=> Fix compile error in 32 bit code.

src/runtime/interp.r
If a thread that is in an initial expression causes a garbage collection
whilst another thread is waiting to execute an initial expression then a
deadlock occurs (because the waiting thread never enters the GC queue,
so the GC thread hangs waiting for all threads to be stopped and
NARthreads to drop to 0).
=> Fix GC deadlock in initial expressions.

src/runtime/rstruct.r
If a garbage collection happens inside hgrow() the bp parameter,
which is not tended, can become invalid leading to the corruption
of the table structure. The fix is to use the tended pointer.
=> Fix GC problem in hgrow().

doc/ib/appA.tex, doc/ib/p1-lists.tex
The previous list-element ptr was drawn with a null terminator.
In Unicon, it terminates with a ptr to the list header block.
=> IB: Correct previous list-element ptr in list diagrams.

doc/ib/appA.tex, doc/ib/p1-procs-coexprs.tex
The pointer to the name of the file containing the declaration
of the procedure (which was deleted from struct b_proc long ago)
has been removed from the diagrams and accompanying text.
=> IB: Update description of procedure blocks.

Makefile, Makefile.in, src/runtime/Makefile
The calculation of the SVN revision number (stored in src/h/revision.h)
was being overridden by the update_rev target in src/runtime/Makefile.
That target is now active only if the file src/h/revision.h does not exist.
A missing newline has been added to src/h/revision.h. and the file is now
removed by the Pure target (since it's a configured file).
=> Adjust Unicon revision to correspond to SVN's revision (take 2).

src/iconc/ccomp.c
The --export-dynamic linker option (used everywhere else) is
called -export_dynamic on macOS. No, I don't know why either.
=> Fix iconc C compiler driver to pass the correct linker option on MacOS.

uni/unicon/unix.icn
The (old) -S options that were passed along if the version was before 8.6
are no longer understood (and, if used, break the build): it's best to remove them.
=> Remove code handling Icon v8.5 and earlier.

uni/lib/object.icn
The fieldNames() method was written for original UniLib version.  This updates it to work correctly with uni/lib changes.
=> Fix fieldNames().

uni/lib/Makefile, uni/lib/struct.icn
Mark struct.icn as deprecated in favor of json.icn.
=> Add some missing files to Makefile fixing file ordering.

src/common/dconsole.c, src/common/filepart.c, src/h/rexterns.h, src/iconc/ctrans.c, src/iconc/yyerror.c, src/icont/tglobals.h
GCC 10 changed the default behavior related to global variables.
These changes break the build when using gcc 10+.
Related: -fno-common flag
https://gcc.gnu.org/gcc-10/porting_to.html
=> GCC 10 Fixes

uni/lib/args.icn
This reverts the Args class' behavior back to that intended by the UniLib version.  The class separates option command line parameters (those that start with one or more hyphens) from non-option arguments (e.g. a list of file names).
=> Revert Args class behavior to UniLib version

ipl/gprocs/vidgets.icn
Without this change, importing both 'gui' and ''util' packages as in:
->cat Test1.icn
import util
import gui
procedure main()
end
->
results in the linking warnings:
->unicon Test1.icn
Parsing Test1.icn: ...
/opt/unicon/bin/icont -c   -O Test1.icn 
/tmp/uni30124935
Translating:
Test1.icn:
main
No errors
/opt/unicon/bin/icont  Test1.u
Linking:
viface.icn: "erase_Vline": undeclared identifier,  procedure VErase
viface.icn: "event_Vtoggle": undeclared identifier, procedure VGetState
->
=> Add vbuttons to vidgets.icn

ipl/procs/paths.icn
When the procedure lpaths() is used in the unicon compiler, the global
variable "iconc" is defined. However, when the lpaths() procedure is used
in other applications, this global will not be defined.
We define it here to prevent the undefined variable message from occurrig.
=> Define missing global variable "iconc" in paths.icn.

ipl/procs/calendat.icn
As the contents of calendat.icn were a direct extract from datetime.icn,
change the file to link to the datetime IPL file. This will allow any
future changes that may be made to datetime.icn to be propagated to any
usage of this file.
=> Replace file contents with link to datetime.icn

Makefile, Makefile.in
The Makefile references README in the Install section instead of README.md.
This fails to copy the README.md document to the documentation directory
when installing.
=> Correcting Makefile install "docs and mans"

uni/gui/dialog.icn
If dialog's parent is set, this defaults the dialog to display centered on that parent.  Can also place dialog anywhere on display, relative to upper-left corner, using position specifications the same as in Component.set_pos(x,y).
=> Allow centering dialog in parent

ipl/procs/numbers.icn
Previously, a new version of large() was added to handle the versions
of Unicon that had concurrency facilities added. Unlike the the old
version of large(), which is still retained in numbers.icn, the new
version failed to return the supplied parameter. This has been changed
to return the supplied value.
=> Update IPL file numbers.icn to fix large() return value

uni/lib/fcn_util.icn
commit 4a0e260f5ca83ad5be56793a2ff44c06fdef0d0e
Author: swampler <av_13@tapestry.tucson.az.us>
Date:   Wed Aug 26 17:37:20 2020 -0700
Avoid name collision in Closure call
This is a minor change to avoid a name collision between a local variable and an object field.
commit 03af501fb2a91efbab62c7e5f5b374e202fe3c0c
Author: swampler <av_13@tapestry.tucson.az.us>
Date:   Tue Aug 25 08:59:22 2020 -0700
Allow string invocation of functions
Allows fcn_util to use string invocation.
Bug fix to invoking a list.
=> Squashed commit of the following:

uni/gui/addressgui.icn, uni/lib/db_util.icn
A) Use standard SQL escapes for backslash and single quote (previous version worked with old PostgreSQL, not standard SQL).
B) GUI event handling has changed from the old GUI support code.  This updates the gui to use the new events.
=> addressbook package fixes

ipl/cfuncs/icall.h, plugins/src/icall.h
The change to IconType (which fixes a bug where it might address beyond
the end of the string) was agreed in May 2017. The two files had minor
incompatibilities; they are now the same. tabs have been converted to spaces.
=> Modify IconType in icall.h and add explanatory comments.

uni/lib/langprocs.icn
This adds a simple convenience method call_by_name(f_name,f_args[]) that invokes the procedure with string name f_name with the arguments given by f_args[]).  It differs from straightforward string invocation in that it
maps package-based procedures (including call constructors) into their internal form prior to doing the string invocation.  It's expected use is in creating class instances based on user-input class names.
=> Add call_by_name()

uni/lib/db_util.icn
The escape() method mishandles backslashes.  This fixes it.
=> Fix escape() method.

ipl/procs/xoptions.icn, tests/general/data/f1.xop, tests/general/data/f2.xop, tests/general/stand/xcommand.std, tests/general/xcommand.icn, tests/samples/f1.xop, tests/samples/f2.xop, tests/samples/xcommand.icn
This file contains an extended (highly modified) version of a command
line argument processing procedure. It includes more POSIX and GNU
command line processing as well as additional changes and extensions.
For testing purposes, there are two files that are included in the
data directory. Uncomment the procedure main() in the xoptions.icn
file, compile and run. The output should be 44 lines of output.
=> Creation of xoptions.icn - replacement for options.icn

doc/ib/appH.tex, src/h/feature.h, src/h/posix.h, src/h/sys.h, src/iconc/ccomp.c, tests/bench/auxiliary.icn, tests/general/prepro.icn, uni/gui/dialog.icn, uni/unicon/preproce.icn
Apart from the config directory (which also contains other fossils)
all instances of the MacOSX definition -- including in &features --
have been replaced by MacOS. The stimulus for this change is to fix an
error reported by clang v12 in rmemmgt.r. Clang v11 warned about the
implicit declaration of sysctlbyname, but let it go. Clang v12 is less
forgiving.
=> Remove traces of MacOSX, replace with MacOS

uni/lib/Makefile
Switch positions of scan_util.u and and str_util.u to fix dependency issue.  Move property.u to the end.
=> Reorder build sequence in Makefile

.github/labeler.yml, .github/workflows/ccpp.yml, .github/workflows/label.yml, .github/workflows/packages.yml, COPYING, Makefile, Makefile.in, configure, configure.ac, debian/changelog, debian/control, debian/copyright, debian/rules, src/gdbm/systems.h, tests/Makefile
This PR includes:
* Expanded continuous integration testing. The CI now covers:
- Ubuntu 18.04 and Ubuntu 20.04
- Ubuntu 20.04 32-bit
- macOS
- Windows 64-bit 
The CI also attempts to build Unicon on Ubuntu 20.04 with different config options:
- No Graphics
- No Concurrency
- Using Clang complier
Work to add Window 32-bit and more config options is ongoing
* Binary Package builds, currently only targeting:
- Ubuntu 18.04
- Ubuntu 20.04 
* PR automatic labels. When a PR is opened on GitHub, it will be labeled based on what
files are being  changed. Example labels are IPL, iconx, and icont.
* Various fixes and updates to debian packaging.
* Silence parentheses-equality warning in clang and drop deprecated fno-unit-at-a-time flag 
* Add OpenSSL License exception text to COPYING
=> Expanded CI coverage and debian build updates

src/h/config.h
Not sure why it was disabled, probably migrated from  an old config.
=> Enable Libz on  macOS

uni/lib/Makefile, uni/lib/pdb_util.icn, uni/lib/property.icn, uni/lib/propertydb.icn, uni/lib/union.icn
Allows the storage and retrieval of properties (name,value) pairs from a relational
database.  Currently PostgreSQL 9.6+ databases are fully supported.   Other SQL
databases may have to subclass the PropertyUtil class (pdb_util.icn) to adjust
the SQL syntax for required actions.  In a property, the value can be any
arbitrary Unicon value, include structures that contain cyclic references.
The original, transient, property implementation is still available and can be
selected via a procedure call.  See the comments in property.icn for details
=> Support persistent properties

Makefile, Makefile.in, src/h/version.h, src/runtime/Makefile, src/runtime/keyword.r, uni/unicon/unicon.icn
The first result is the string from version.h (exactly as before).
Subsequent results give details from the build (the output from
git describe --long HEAD) and the name of the branch that the software
was built on. The Unicon compiler uses the information to build a
more informative output when the -version option is given.
=> Make &version a generator.

.gitignore, uni/unidoc/Makefile, uni/unidoc/UniAll.icn, uni/unidoc/UniDoc.icn, uni/unidoc/UniFile.icn, uni/unidoc/UniForm.icn, uni/unidoc/UniHTML.icn, uni/unidoc/UniToken.icn, uni/unidoc/buildDocs.sh, uni/unidoc/buildIPLdoc.sh
The UniDoc sources now compile and run using the uni/lib support instead of the old UniLib librareis. 
Note that the build*.sh scripts require customization for each system they are run on to propertly locate the Unicon source hierarchy.
=> Updated UniDoc for use with uni/lib

doc/utr/utr20.tex, tests/lib/jsontests.icn, uni/lib/json.icn
1) Added proper Unicon/JSON escape conversions.
2) Changed internal procedure names and comments to be more consistent.
3) Added cset support
4) Added jtous() and jtouf() as library functions (will update UTR20 later)
Signed-off-by: Gigi Young <kzyoung93@gmail.com>
=> JSON library update

doc/ib/appD.tex, src/h/rexterns.h, src/runtime/rdebug.r
Two debugger helper functions have been defined with --enable-devmode.
dbgUFL()     print current Unicon file and line number.
dbgUTrace()  print a Unicon stack traceback.
A section describing their use has been added to Appendix D of the IB.
=> Extra debugging help in DEVMODE.

Makedefs.in
If the branch name is the same name as a tag (which will happen on
long term maintenance branches) using git rev-parse to extract the
branch name results in extra information to make it "non-ambiguous".
Using git branch --show-current always returns the branch name with
nothing added.
=> Always use the unvarnished branch name when building.

uni/lib/scan_util.icn, uni/lib/union.icn
In scan_util.icn, the code for moveMatch() is cleaned up and the header
comment adjusted to reflect the actual behavior.
In union.icn the decoding of class and record UniON strings is simplified and a
potential conflict arising from conflicts between user-defined class fields and
the internal class fields is addressed.
=> Minor updates to union.icn and scan_util.icn

doc/book/langref.tex, src/runtime/fstruct.r
This is an update from Clint to add a test for whether a string is a
field name in a record (as described in section 2.3 of the Unicon book).
=> Add records to member().  Patch from Clint.

doc/utr/utr20.tex, uni/lib/json.icn
-The library incorrectly removed eight fieldnames from Robert Parlett's
class "Class".
-Additionally, amended the date of UTR20.
Signed-off-by: Gigi Young <kzyoung93@gmail.com>
=> JSON library bug fix

configure, configure.ac, ipl/cfuncs/Makefile
Also move building the cfunc dynamic library from a script to the Makefile
=> cfuncs: drop unnecessary dylib linker option

uni/unicon/Makefile, uni/unicon/unigram.icn, uni/unicon/unigram.u, uni/unicon/unigram.y
Details: There is an else in unigram.y (on line 346) that needs to be
removed so that after the warning, the class is still looked up, inserted, etc.
=> Fix Unicon compiler crash after emitting a warning (Patch from Clint)

config/scripts/version.sh, src/h/version.h
config/scripts/version.sh is responsible for versioning.
Version date is extracted from the commit date.
Tarballs must be created after running the configure script once.
Fall back to old method if everything else fails
=> Script version and date, date is extracted from the last commit

doc/book/graphics.tex
Superfluous parameter to Event() removed. Extra height parameter to
getacolor() added. Note that ipl/gprogs/pme.icn and the book listing
are different; the book listing appears to be later.
=> Corrections to pme listing (chapter 7 of Unicon book) from Bruce Rennie.

src/runtime/rwindow.r
=> iconc: force clang to not ignore flog on macOS

uni/unicon/preproce.icn
This patch from Clint fixes an error in the preprocessor that counted
an incomplete string literal line (one ending with a _ character) twice.
=> Fix line count error when handling incomplete string literals.

doc/book/classes.tex
It suggested that procedure declarations are permissible inside a
class declaration: they aren't.
=> Fix fossil in section 10.4 of the Unicon book.

src/iconc/cmain.c, uni/unicon/unicon.icn
As well a dealing with a build where we are not on any branch, the logic
now treats whether the head revision is tagged as more important than
the branch name. Previously the branch name trumped the tag.
=> Tweak versionLine to deal with detached HEAD.

uni/unicon/preproce.icn
This patch from Clint fixes a Unicon preprocessor bug -- definitions from
previous files were still active on subsequent files on the command line.
=> Fix preprocessor to not retain definitions from previous files.

doc/ib/app-solutions.tex, doc/ib/p1-exprEval.tex, doc/ib/p1-iconOverview.tex, doc/ib/p1-interpreter.tex, doc/ib/p1-intro.tex, doc/ib/p1-lists.tex, doc/ib/p1-organization.tex, doc/ib/p1-procs-coexprs.tex, doc/ib/p1-runTime.tex, doc/ib/p1-sets-tables.tex, doc/ib/p1-storage.tex, doc/ib/p1-strings-csets.tex, doc/ib/p1-values.tex
Replace the hard coded chapter numbering used in the exercises (and
answers) in part 1 by LaTeX \labels and \ref*. This makes it easier to
introduce new material or to rearrange the order of the chapters.
=> Fix exercise numbering in part 1 of the IB.

uni/lib/class.icn
There is a difference between what classname() returns and the original langprocs
procedure get_class_name(). This was discovered when trying to run the program ui.
The former does not return the package name as part of the classname() but did so
with the original get_class_name() langproc procedure.
A change has been made to the class Class to get the list of methods directly using
the obj supplied instead of the class name returned using the Unicon function classname().
The ui program works correctly with this change.
=> Update the methods list collection for supplied object

src/rtt/rttout.c
clang complains about the extra parentheses output (by rtt) when emitting code
for is:null etc.. The best thing would be to modify rtt so that the extra
parentheses were only emitted if they were really necessary. The easiest thing
would be to shut clang up about it globally. The easy thing is to shut clang up
only during the is:thing code. We do the easy thing.
=> Suppress clang warnings produced by rtt code for is:thing

src/common/mlocal.c, src/h/opengl.h, src/runtime/fmisc.r, src/runtime/fsys.r, src/runtime/rmemmgt.r, src/runtime/rmisc.r, src/runtime/ropengl.ri, src/runtime/ropengl2d.ri, src/runtime/rsys.r, src/runtime/rwindow.r, src/runtime/rxrsc.ri, src/runtime/rxwin.ri
Most of the warnings are dealt with by addressing the complaint(s),
rather than suppressing the warning messages.  Some of the more
difficult issues have been left for a later effort but, with these
changes, the number of warnings is reduced to about one sixth of its
former value (~600 --> ~100 ).
=> Reduce the number of warnings produced by clang.

src/common/error.h, src/common/xwindow.c, src/gdbm/systems.h, src/h/rproto.h, src/iconc/ccode.c, src/iconc/codegen.c, src/iconc/incheck.c, src/iconc/tv.c, src/iconc/typinfer.c, src/icont/tmain.c, src/rtt/rttmain.c, src/runtime/cnv.r, src/runtime/fload.r, src/runtime/fstruct.r, src/runtime/fxpattrn.ri, src/runtime/interp.r, src/runtime/rdebug.r, src/runtime/rposix.r
Most of the warnings are dealt with by addressing the complaint(s),
rather than suppressing the warning messages.  Some of the more
difficult issues have been left for a later effort. This commit
eliminates approximately 70 warnings.
=> Reduce the number of warnings produced by gcc.

src/Makefile, uni/Makefile
When iyacc moved from uni to src we forgot to amend make Pure. The result is
on a subsequent build make thinks that there is nothing to be done for iyacc
and doesn't move the iyacc binary to the bin directory. The build then fails
because iyacc isn't available.
=> Fix build failure after make Pure.

src/runtime/init.r
=> runtime: use stat() not lstat() to allow us follow symlinks

uni/lib/object.icn
The Unicon function classname does not return the package that a class is in.
This affects UniDoc and causes an abort in the operation of UniDoc.
The change to object.icn in the lib has been adjusted to fix this error.
=> Fix for object.icn to obtain class names with package.

src/runtime/fstruct.r
The original classname() function removed the package part of a class name.
This change is to include the package name as a part of the class name.
The only line actually affected is line 692. This line is removed from the source. Other changes are due to my editor automatically removing extraneous spaces at the end of any line.
This change ensures that the package information is kept when getting the class name of the object selected.
=> Update function classname() to return package as well.

uni/lib/object.icn, uni/lib/predicat.icn
Simplify className() and Type() methods now that the classname procedure returns fully-qualified class names.
Signed-off-by: Steve Wampler <sbw@tapestry.tucson.az.us
=> Update to use repaired classname()

uni/lib/args.icn, uni/unidoc/UniAll.icn, uni/unidoc/UniDoc.icn, uni/unidoc/UniHTML.icn
This adds the ability to detect bad command line options to the util::Args class and adds that detection to UniDoc.  A bug in UniDoc where the handling of a default target directory is incorrect has also been fixed.
=> Update to Args class and UniDoc option handling.

Makefile, uni/unidoc/Makefile, uni/unidoc/UniDoc.icn, uni/unidoc/buildDocs.sh, uni/unidoc/buildIPLdoc.sh
To be consistent with the naming convention used with other Unicon tools, this changes the name of the UniDoc tool to unidoc.
=> Rename UniDoc executable to unidoc

uni/unidoc/UniAll.icn, uni/unidoc/UniDoc.icn
When a directory name is given as an argument to UniDoc,  all Unicon/Icon source files in that directory
(but not subdirectories) are processed.
=> Allow directory names as arguments

plugins/src/icall.h
Add a new macro to check that a parameter is a native integer, not a
large one, and add the definitions for D_Lrgint etc. to icall.h
=> Add lrgint to icall.h

plugins/src/bitman/Makefile, plugins/src/bitman/bitman.c, plugins/src/bitman/bitman.h, plugins/src/bitman/bitman.icn, plugins/src/bitman/testbitman.icn
The routines are the equivalent of the Unicon built-in functions
except they never produce a large integer and there is no special
case for the sign bit.
bor      bitwise inclusive or       (ior)
bxor     bitwise exclusive or       (ixor)
band     bitwise and                (iand)
bcom     bitwise one's complement   (icom)
bshift   bitwise shift              (ishift)
plus
bits     enquiry and bit extraction
bit      single bit extraction
brot     bit rotation
bit(x,n) works the same way as string indexing (but indexing bits instead
of characters, including negative indices meaning "from the end").
bit(x,1) is the ls bit of x,      (analogous to s[1]).
bit(x,n) is the nth bit of x      (analogous to s[n] when n is +ve).
bit(x,0) is the ms bit of x       (analogous to s[0]).
bit(x,-n) is …
=> Add a bit manipulation plugin.

src/h/rexterns.h, src/runtime/init.r, src/runtime/rmemmgt.r
The log buffer size may be varied by defining VRFY_LOGSIZE in define.h
The "x is verified" log messages are controlled by an environment
variable VRFYOP which has a bit set for each type that the "is verified"
message is desired. (e.g. for records the value is 1<<T_Record = 128).
=> Add control over the size and contents of the heap verifier log buffer.

plugins/src/upexample/Makefile
The addition of Clean allows each individual plugin to specify specific
clean up actions in addition to the standard clean actions.
=> Add a Clean target to the upexample makefile.

.github/workflows/build.yml
The build failed because the diff program was missing from the Fedora
container used to perform the build (patch supplied by Jafar).
=> Fix Fedora CI build failure.

.github/workflows/build.yml
Instaling more dependencies enables more features in the build
allowing for better test coverage
=> ci: install more dependencies for Fedora and CentOS

src/runtime/fsys.r, src/runtime/rposix.r
Setting the default IP address family to  AF_UNSPEC allows an application to work with both 
ipv4 and ipv6. The user can still specify 4 or 6 when opening a socket to force a specific 
address family.
=> runtime: default to AF_UNSPEC if no specific IP protocol is selected

ipl/procs/base64.icn
The previous version discarded all trailing null characters: it should
only discard the number specified by the padding.
=> Fix base64decode().

uni/lib/misc_util.icn
Two new PDCOs that allow experimenting with evaluating result sequences in pseudo-parallel fashion.  In both cases, the result sequences are stepped through and the PDCO suspends once all result sequences have been evaluated to produce a result.  One PDCO fails if any of the sequences is empty and the other fails only after all of the sequences are empty.
The hope is that the behavior of one or both of these PDCOs can be useful enough that someone  will integrate that behavior, or something similar, into the Unicon syntax.  (Fixing the scoping limitation imposed by the use of PDCOs.]
=> Allow experimenting with "parallel" result sequence evaluations

uni/ide/funclookup.icn
Add to method load_reserved_words the missing reserved word "abstract".
Add to method load_BInames() the missing internal functions and remove
the extraneous reserved words.
=> Add missing reserved word and internal functions

src/runtime/fsys.r, src/runtime/rposix.r
When IPv6 support was added I was passing `is_udp_or_listener` to mean udp. It is only upd 
if `is_udp_or_listener == 1`
I tested a tcp server with listener socket and it works now.
=> Fix listener sockets

src/runtime/fxposix.ri
select() accepts files or a list of files, but it is useful
to also have support for a set of files. When managing a large
number of sockets it is convenient to maintain the sockets in a set
since a socket can be easily found using member() instead of looping
through a list.
=> Allow select() to accept a set() as an argument

src/runtime/rposix.r
When calling open() n mode "na", we ask for a TCP socket but without
going through an explicit listen(). In that mode, the call to open()
should be blocking, unlick a listener "nl"  mode. In "na" case we
still want to call listen() first, then invoke acceptto block.
=> Fix socket accept mode

src/h/sys.h
=> remove defs of sys functions before we do 'include'

doc/book/langref.tex
The current description for ishift is inaccurate (claiming that zeros
are introduced on both shift directions). Replace it with icon's description,
which also includes sign extension for negative shifts.
=> Fix documentation for ishift.

plugins/src/Makedefs, plugins/src/Makefile, plugins/src/SHA/Makefile, plugins/src/SHA/RFC6234/makefile, plugins/src/bitman/Makefile, plugins/src/lxcunicon/Makefile, plugins/src/template/Makefile, plugins/src/upexample/Makefile
SHA and bitman are now built by default.
Typos have been corrected.
Plugin specific clean up is now done via a clean:: target (the example
files have been corrected).
=> Build SHA and bitman plugins by default. Allow plugin specific clean up.

src/runtime/fload.r
The plugin library (/usr/local/lib/unicon/plugins/lib) is searched if
the specified library has not already been located.
=> Fix loadfunc() to search the installation directory for plugins.

doc/book/experimental.tex
Everyone's favorite:  it's --> its
=> Fix typo in Appendix G of Unicon Book.

plugins/src/SHA/Makefile, plugins/src/bitman/Makefile
The build error sometimes happened with make -j8 (building the
shaPlugTest program failed because the shared library wasn't built
yet). Fixed by making a separate test target. The cosmetic issues were
to remove trailing spaces and duplicate definitions.
=> Fix a build error and cosmetic issues in SHA and Bitman plugins.

src/gdbm/testgdbm.c, src/gdbm/testndbm.c
Some (perhaps most?) key and data pairs in uniclass.dir are not null
terminated (there is a dsize field, which is correct, but testgdbm and
testndbm didn't use it) resulting in extra garbage characters being
displayed after the key and data. The fix is to use a precision spec
in the printf format strings.
=> Fix key and data display of testgdbm and testndbm.

config/editor/unicon.sublime-syntax
Tweak the Unicon syntax definition for Sublime Text 3:
* Fix Comments scope:
* Fix `comment.line.double-slash` to `comment.number-sign.dollar`.
* Fix Keywords:
* Improve readability of `reserved` and `keywords` contexts by enabling free-spacing mode in their RegEx definitions.
* Fix `keywords` definition which failed to match some keywords.
* Improve Preprocessor:
* Fix `comment.line.double-slash` scope to `comment.line.dollar`.
* Add `meta.preprocessor` scope to matched line.
* Improve Operators:
* Tweak scope from `keyword.control` to `keyword.operator`.
* Extend operators definition to include: % + - ^
* Characters Sets:
* New context to capture also single-quoted strings.
* Include escapes sequences context.
* Improve Escape Sequences:
* Move escapes definition to independent context …
=> Sublime Syntax: Fixes & Improvements

config/editor/README
Edit `config/editor/REAMDE` to mention the new Unicon package for Sublime Text 4:
- Rename existing "Sublime Text" section to "Sublime Text 3".
- Add new "Sublime Text 4" section with a link to the the   package page and installation instructions.
=> Link to New Sublime Unicon Package

doc/book/langref.tex, src/runtime/data.r, src/runtime/fsys.r
Handle failure of popen(). Distinguish between a successful command that
produces no output and a non-zero return status from the command.
Document new (and not so new) error numbers in Appendix A.
=> Improve treatment of no output from a piped command.

src/runtime/fxposix.ri, src/runtime/rposix.r
Some calls to select() and accept() were preventing GC from taking place.
=> Fix indefinite wait for GC

Makefile, Makefile.in
These don't work anymore, and people still try to use them sometimes.
=> build: drop legacy makefile rules

tests/lib/jsontests.icn, uni/lib/json.icn
`utoj()` encodes unicon types when it writes json data.
Example:
if we feed the following json data to `jtou()`:
```
{"name":"Joe","age":42,"gender":"Male"}
```
The tabel in memory:
```
T2 := table(&null)
T2["age"] := 42
T2["gender"] := "Male"
T2["name"] := "Joe"
```
`utoj()` produces it as:
```
{"__unitable__":1,"gender":"Male","name":"Joe","age":42}
```
whereas the new `tojson()` function produces the original json data as:
```
{"gender":"Male","name":"Joe","age":42}
```
`utoj()` is good to encode Unicon data structures to be decoded properly
later in another Unicon program.
`tojson()` cares about json data only, not about Unicon meta data.
=> New tojson() function that writes json without encoding unicon types

doc/ib/p2-codeGen.tex, doc/ib/p2-iconcOrg.tex, doc/ib/p2-liveness.tex, doc/ib/p2-overview.tex, doc/ib/p3-2D3D.tex, doc/icon.sty, doc/utr/icon.sty
I'm not sure whether to wait for the results (if any) of people building the IB on various platforms to see if the "Tab Overflow" fix works for them. But, since the IB is not part of the regular Unicon build, on balance I think it's better to commit it now and fix any problems that arise as and when they surface.  There is more information in the separate commit messages.
=> Fix Tab overflow and TikZ missing character messages.

doc/utr/utr20.tex
On some platforms (Debian Bullseye with TeX-live 2022) an error is generated on line 47 "! LaTeX Error: \verb ended by end of line." Others -- MacOS 12 with TeXShop (TeX-Live 2020) -- work without error.
=> Fix utr20.

configure, configure.ac, doc/ib/appD.tex, src/h/auto.in, src/h/fdefs.h, src/h/feature.h, src/h/rexterns.h, src/runtime/rdebug.r
DEVMODE clashes with a type name inside the Windows UCRT library and causes a build failure if --enable-devmode is given as an option to configure. The --enable-devmode and the _DEVMODE preprocessor defined symbol have not been renamed to avoid breaking existing usage.
=> Rename DEVMODE to DEVELOPMODE.

src/runtime/rxwin.ri
PBuffer seems to be deprecated. glXCreatePbuffer fails on MacOS. So the GL 2D implementation still needs a fix, but this patch allows 3D graphics to work again at least.
=> runtime: initialize a window pbuffer only if the window is GL2D

src/iconc/ctrans.c, src/runtime/keyword.r, uni/parser/preproce.icn, uni/unicon/Makefile, uni/unicon/nocchelper.c, uni/unicon/preproce.icn
Allow `_CONCURRENT` to be a built in Unicon preprocessor definition with `iconc` or `unicon -C` if the system has been configured with `--enable-iconcurrency`.
=> Fix _CONCURRENT

plugins/src/SHA/shalib.c
All functions that are exported from a dll must have __declspec(dllexport)
=> Fix SHA plugin on Windows.

plugins/src/SHA/shalib.icn
The SHA code detects record types by using a "none of the above" approach. So it needs to explicitly fail patterns to avoid them being treated as records.
=> Update SHA plugin to handle (i.e fail)  patterns.

plugins/src/sqlite/sqlite.c
All functions that are exported from a dll must have __declspec(dllexport)
=> Fix SQLite plugin on Windows

plugins/src/SHA/shalib.icn
They don't add any value and can be replaced with other calls. e.g.
s.Sha_Input(x, ...)   ->    s.Sha(x, ..., More)
s.Sha_Result()        ->    s.Sha()
s.Sha_RawResult()     ->    s.Sha(Raw)
s.Sha_ShaFunction()   ->    s.shaF
s.Sha_ShaFunction(x)  ->    s.Reset(x)
etc.
Leaving them in would mean adding extra test code and documentation, so
it's better to remove them.
=> Remove direct access methods from the SecureHash plugin.

src/iyacc/reader.c
Tweak iyacc to interpret "$$=" as "$$:=" under Icon/Unicon, allowing the same .y file to work for both Unicon and Java, for example.
=> add $$= syntax

src/runtime/rmemmgt.r, src/runtime/rstruct.r, uni/progs/gcfreq.icn
The locations are specified by filename and line number. Also
Clean up the log output if no detailed verifications are being performed
so that there is more space for the locations.
Remove a log entry from hgrow(), which was left in by mistake.
Add a small utility program that displays the most common locations.
=> Add Unicon program locations causing GC to the heap verifier log.

src/runtime/rmemmgt.r
The size calculation for integer and real arrays omitted the size of the header, causing spurious verification failures.
=> Fix heap verification of arrays.

src/runtime/rmswin.ri, src/runtime/rxwin.ri
Previously, "mono" and "fixed" were treated as the same thing and asked for Lucida Sans, which is a proportionally spaced font. Now, "mono" asks for Lucida Console, which is monospaced, and "fixed" selects Lucida Sans (with the correct flags).
=> runtime: Make "mono" select a monospaced font.

.vscode/extensions.json, .vscode/settings.json, .vscode/tasks.json, .vscode/unicon.code-workspace
Add extensions suggestions
Add common build, configure, and tests tasks.
Tasks can be invoked from vscode command menu or via shortcuts.
=> add default vscode configs and extension recommendation

.gitignore, .vscode/tasks.json, tests/Makefile.test, tests/general/ssl.icn, tests/posix/getserv.icn, tests/posix/stand/getserv.std, tests/posix/udp.icn, tests/posix/uxsocket.icn, tests/thread/sharelist.icn, tests/thread/sum.icn, tests/unicon/FxPtTest.icn, tests/unicon/FxPtTest_OVLD.icn, tests/unicon/Makefile
If the test standard output contains the text "This program requires", the test is considered skipped and the output is reported as is. Ex:
```
[Testing utf8]... OK
[Testing utf8_ovld]... This program requires operator overloading.
[Testing var]... OK
```
=> tests: fix a few posix issues. Skip test if feature isn't supported

uni/unicon/unicon.icn
Two identical branches in a case expression means that the second branch is never executed! (So merge the two -K branches into one).
=> Implement Unicon -K properly

doc/ib/appH.tex, doc/ib/ib.tex, doc/ib/p1-storage.tex
Allow removed definitions in Appendix H to be coloured in grey.
=> Preparation for source code tidy up.

doc/ib/appH.tex, src/runtime/imain.r
It isn't used anywhere. It's either a vestige of something that has been removed or it's the start of something that was never completed.
=> Remove definition of MaxLevel.

uni/lib/complex.icn
The present optimising compiler has problems with the complex class. The workaround(s) are to remove the Object superclass and to provide an initially section to set the default values.
These changes can be reverted when the problems are solved.
=> Complex class: Workaround Unicon -C problems.

src/runtime/rstruct.r
Warnings were generated with either --enable-iconc or --enable-debugheap.
iconc: warning: variable 'chainlen' set but not used [-Wunused-but-set-variable]
debugheap: warning: variable 'elemtitle' set but not used [-Wunused-but-set-variable]
=> Fix clang warnings in rstructs.r

src/runtime/rmsg.r
The  Mhttp and Msmtp routines both use Maddtoheader() which uses strncat to fill up the buffer and append a trailing zero char after each append. Mhttp initialises hleft to sizeof(header) - 1, which leaves space for a terminating zero char, even if the header becomes full. Msmtp initialises hleft to sizeof(header), which means a buffer overflow is possible.
=> Fix possible buffer overflow in rmsg.r

src/h/rt.h
This commit removes the implicit-function-declaration warnings.
=> Declare flock() for Windows builds.

.github/workflows/build.yml, src/common/Makefile, src/common/dconsole.c, src/runtime/keyword.r
silence a clang warning when compiling rswitch.s
fix Windows warnings
=> src: fix clang and Windows warnings and enable werror on both

src/common/dconsole.c, src/runtime/fsys.r, src/runtime/fxposix.ri, src/runtime/init.r, src/runtime/rmswin.ri, src/runtime/rsys.r
The fix consists mostly of moving routines that are not graphics oriented to places that included them even if Graphics is not defined.
=> Fix build errors on Windows when using --disable-graphics

src/runtime/rmisc.r
The Blk macro cannot be used if null is an expected parameter; it will always cause a crash if debugHeap is enabled.
=> Fix pattern test failures when debugHeap is enabled

src/runtime/fxpattrn.ri
The src and dest arguments to strncpy were the same. The manual says
The source and destination strings should not overlap, as the behavior is undefined.
=> Fix questionable use of strncpy in pattern code.

.github/workflows/build.yml, Makedefs.in, configure, configure.ac, ipl/cfuncs/fpoll.c, src/common/Makefile, src/h/auto.in, src/iconc/Makefile, src/icont/Makefile, src/iyacc/Makefile, src/preproc/Makefile, src/rtt/Makefile, src/runtime/Makefile
* `--enable-devmode=all` now enables DebugHeap and DebugVerify
* DebugHeap/Verify are reported as part of the config summary
*  Report `CFDYN` and `LDDYN` in config summary
* Don't strip in debug mode
* Detect MUSL C library
* MUSL needs `no-pie`
=> config: improve debug options/reporting, strip, musl

src/iyacc/main.c
The prefix for the generated file name should be the string before the last dot in the filename, not the first. (Reported by Bruce Rennie).
=> iyacc: Fix bug when generating file names.

uni/gprogs/qmazer.icn, uni/progs/complex_ex.icn, uni/progs/rankvote.icn
One demonstration of 2D graphics and two programs showing example use of various uni packages.
=> A few simple programs demonstrating different features of the uni library

uni/ulsp/server.icn
Fixes unhandled case where client hasn't finished sending data for body of a header + body pair.
=> ulsp: socket reading fix

src/h/rproto.h, src/runtime/init.r
This is causing crashes in other parts of systems/libraries we link to if they happen to call getrandom()
=> runtime: avoid name collision with getrandom from libc

uni/lib/database.icn
To be honest, I don't understand how the original version ever worked as the arguments to open() aren't correct according to the documentation.  Yet it used to work but now doesn't.  This new version fixes that.
=> Fix call to open() on a database.

uni/ulsp/launch-lsp.icn, uni/ulsp/server.icn
=> ulsp: add run mode (server -s and client -c)

Makefile, Makefile.in
Adding the ulsp directory to /usr/local/lib/unicon fixes a crash in build_bnf() at start-up.
=> Fix install of ulsp.

uni/unidoc/UniFile.icn
Fixes the problem UniDoc has with procedures ending with a single-line compound expression.  Also fixes a related issue with the handling of continued csets and strings under the same conditions.
=> Fix UniDoc's handling of single-line compound expressions.

doc/book/langref.tex
It's possible to read the present description as specifying that ready() always fails if there is no input available. This clarifies that failure can only occur if the second parameter is not zero.
=> Clarify the behaviour of ready() in the Language Reference.

src/runtime/rposix.r
It was possible to overrun the strings region leading to corruption of memory. The new code checks for overrun and allocates a new buffer if it would occur.
=> Fix bug in u_read()

doc/book/langref.tex
Also clarify that the defaults are based on the corresponding sizes for the main thread (rather than all being based on heap size).
=> Document the fourth parameter of spawn() in the language reference

plugins/src/SHA/shalib.icn, plugins/src/bitman/bitman.icn, plugins/src/sqlite/sqlite.icn
The first parameter of find_method() must be an object, which was missing in the SHA, Bitman and SQLite plugins.
=> Correct the use of find_method in the plugin api method.

src/xpm/lib/xpm.h
If _POSIX_C_SOURCE is defined, it suppresses the inclusion of machine/_types.h which causes wait.h to fail because
__DARWIN_BYTE_ORDER and __DARWIN_LITTLE_ENDIAN and __DARWIN_BIG_ENDIAN are all undefined.
=> Fix build failure on macOS with Apple's arm processor.

doc/book/thread.tex, tests/thread/critter.icn, tests/thread/stand/critter.std, uni/unicon/tree.icn, uni/unicon/unigram.icn, uni/unicon/unigram.u, uni/unicon/unigram.y
Any mutexes locked by using the critical mtx: syntax will be automatically
unlocked when the critical region is left. Nested critical regions are supported
as is leaving a subset -- for example when breaking out of a loop.
=> Auto unlock critical regions

tests/unicon/FxPtTests.icn, tests/unicon/Makefile
All but one of the FxPt tests succeed. Disable the one test that causes a crash pending an investigation.
=> tests: Disable the one FxPt test that crashes; enable the rest.

src/runtime/rxwin.ri
We can't queue an event to a window after closing it. Move the queue call before we call wclose().
Simplify the code a bit in the process.
=> runtime: fix null pointer deference on a window close

doc/utr/Makefile, doc/utr/utr23.tex, doc/utr/utr23/utr23.sty, tests/lib/unittest.icn, uni/lib/unittest.icn
=> Introducing Unit Test Framework

uni/ulsp/Makefile, uni/ulsp/database.icn, uni/ulsp/file_handler.icn, uni/ulsp/folding.icn, uni/ulsp/lsif.icn, uni/ulsp/server.icn, uni/ulsp/symbols.icn
Added support for textDocument/documentSymbol and textDocument/foldingRange requests in ULSP. Modified filehandler.icn to store ranges of symbols for use in other handlers.
=> Add symbol and folding request handling

uni/unicon/unicon.icn, uni/unicon/unigram.icn, uni/unicon/unigram.u, uni/unicon/unigram.y
The previous method (of defining a PRINT_AST environment variable) to cause the compiler to print out  the Abstract Syntax tree still works.
=> Add a -printAST option to the compiler

uni/ide/ivib/main.icn
7d4093ae changed the compute_absolutes() method in the Dialog class. A side effect of this change is that the coordinates of ivib's main dialog were no longer set to (0,0) before the dialog is displayed by custom_show(), which led to extra space in the dialog window (and an ivib crash under some circumstances).
The smallest, and probably safest, fix is to set the coordinates explicitly in the custom_show() method.
=> Fix ivib to cope with changes in commit 7d4093ae.

doc/book/langref.tex
Correct the name of the receive operators (from @< and @<< to <@ and <<@). Remove a spurious pair of parentheses.
=> Correct typos in the language reference section of the book.

uni/ulsp/Makefile, uni/ulsp/file_handler.icn, uni/ulsp/folding.icn, uni/ulsp/formatting.icn, uni/ulsp/lsif.icn, uni/ulsp/server.icn, uni/ulsp/symbols.icn, uni/unidoc/UniAll.icn
=> Add formatting response to ULSP

doc/book/diffs.tex, doc/book/langref.tex
These keywords are generators.  Add the incompatibility (with Icon) to appendix E of the Unicon book.
=> Fix documentation of &clock and &dateline.

uni/lib/fastprime.icn, uni/lib/matrix_util.icn
Adds a Miller-Rabin primality test for large integers and fixes some typos in the matrix_util.icn file.
=> Support large integer primes, fix typos in matrix_util.icn

.github/workflows/packages.yml
Windows 2025 github images don't include InnoSetup. For now, stick with 2022 image.
=> ci: win 2025 images no longer include inno setup, stick with 2022
